- .github/workflows/assigned-issues-inprogress.yml
- app/public/actions/download.php
- app/public/actions/login.php
- app/public/actions/logout.php
> :bug: (Firefox) Attachments with spaces in name don't download correctly

- .github/workflows/assigned-issues-inprogress.yml
- app/includes/app_functions.php
- app/public/actions/download.php
- app/public/index.php
> 🐛 Display only open subscribed requests on home dash

- app/includes/app_functions.php
Signed-off-by: Luke Tainton <luke@tainton.uk>
Merge from main
> :bug: Fix get open subs error

- app/includes/app_functions.php
> Fix semicolon

- app/includes/footer.php
This PR adds a 'subscribe' button to the footer, allowing users to subscribe to the FHeD user mailing list.
Fixes #91 
Signed-off-by: Luke Tainton <luke@tainton.uk>
> :chart_with_upwards_trend: Add mailing list subscription button

- app/includes/footer.php
Signed-off-by: Luke Tainton <luke@tainton.uk>
> :chart_with_upwards_trend: Add mailing list subscription button (#92)

- app/includes/footer.php
The subscribe button has been fixed, and the footer has been changed slightly to make it easier to position the elements.
Fixes #96 
Signed-off-by: Luke Tainton (<luke@tainton.uk>)
> :bug: Subscribe link works now

- app/includes/footer.php
Change mailing list to Google Groups, and add modal to ensure users know what they're signing up for.
Fixes #99
> :sparkles: Move mailing list to Google Groups

- .github/workflows/deploy.yml
> :construction: Update deploy script to automate versioning

- .github/workflows/deploy.yml
> Fixing YAML Issue

- .github/workflows/deploy.yml
> Fixing Fixing YAML

- .github/workflows/deploy.yml
> Fixing Fixing Fixing Deploy

- .github/workflows/deploy.yml
> Fixing Fixing Fixing Fixing Deploy

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/document_issue.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/issue-branch.yml
- .github/workflows/autobranch.yml
- .github/workflows/deploy.yml
- .github/workflows/stale.yml
> Forgotten Bump

- .github/workflows/deploy.yml
> Fix auto deployment and versioning

- .github/workflows/deploy.yml
> :bug: Remove 'env' sections

- .github/workflows/deploy.yml
> :bug: Make it plural!

- app/includes/app_functions.php
- app/public/actions/login.php
This PR ensures that any errors with the login flow are caught.
Related to #69
> :bug: User not added to DB - force die() on error

- app/public/actions/login.php
> Fixing Login Die

- app/includes/footer.php
- app/public/actions/login.php
> Broken login

- app/includes/footer.php
This PR moves the `<br>` tag in the footer to the start of the second line, where it will only exist if required.
> Move break rule in footer

- app/includes/prereqs.php
Can't add Alex to Sentry without paying, so I moved to GlitchTip hosted.
> :construction: Migrate from Sentry to GlitchTip

- .github/workflows/deploy.yml
This PR fixes the issue where the new image wasn't being pulled on the server.
Fixes #140
> 🐛 Update docker-compose config location
